<a href="https://colab.research.google.com/github/allankeiiti/googleCollab-notebooks/blob/main/Matmul_(Multiplica%C3%A7%C3%A3o_entre_Matrizes).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
print(tf.__version__)

Instructions for updating:
non-resource variables are not supported in the long term
2.4.0


In [2]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[-1, 3], [4, 2]])

In [3]:
multiplicacao = tf.matmul(a, b)

In [5]:
with tf.Session() as sess:
  print(f'{sess.run(a)}\n')
  print(f'{sess.run(b)}\n')
  print(sess.run(multiplicacao))

[[1 2]
 [3 4]]

[[-1  3]
 [ 4  2]]

[[ 7  7]
 [13 17]]


In [6]:
c = tf.constant([[1, 2], [3, 4], [5, 10]])
d = tf.constant([[-1, 3, 10], [4, 2, 30]])

multiplicacao_2 = tf.matmul(c, d)

In [7]:
with tf.Session() as sess:
  print(f'{sess.run(c)}\n')
  print(f'{sess.run(d)}\n')
  print(sess.run(multiplicacao_2))

[[ 1  2]
 [ 3  4]
 [ 5 10]]

[[-1  3 10]
 [ 4  2 30]]

[[  7   7  70]
 [ 13  17 150]
 [ 35  35 350]]
