<a href="https://colab.research.google.com/github/allankeiiti/googleCollab-notebooks/blob/main/PlaceHolders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## O que são PlaceHolders? (Espaço Reservado)
No TensorFlow um PlaceHolder são variáveis que vão receber algum dado futuramente durante a execução de código. Permitindo criar operações e construir um grafo computacional sem necessidade de dados.

Quando atribuimos um dado ao placeholder, estamos ***"Alimentando-o"***

In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
print(tf.__version__)

Instructions for updating:
non-resource variables are not supported in the long term
2.4.0


In [2]:
p = tf.placeholder('float', None)

operacao = p + 2

# Alimentamos o placeholder pelo parâmetro "feed_dict"
with tf.Session() as sess:
  resultado = sess.run(operacao, feed_dict={p: [1, 2, 3]})

In [3]:
print(resultado)

[3. 4. 5.]


In [4]:
p2 = tf.placeholder('float', [None, 5])
operacao2 = p2 * 5
dados = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
with tf.Session() as sess:
  resultado = sess.run(operacao2, feed_dict={p2: dados})
  print(resultado)

[[ 5. 10. 15. 20. 25.]
 [30. 35. 40. 45. 50.]]
